app:
  app_name: "StarPDF"
  app_version: "3.0.1"
  default_theme: System
  default_color_theme: blue
  icon_sun: assets/icons/sun.png
  icon_moon: assets/icons/moon.png
  app_icon:
  icon_home: assets/icons/home.png

normas_predefinidas:
  - "Durante la presentación inicial, los participantes deben mantenerse en silencio, salvo que se les pida intervenir."
  - "Para abrir un debate sobre cualquier tema, se deberá presentar previamente una propuesta concreta."
  - "El debate formal se realizará únicamente en el punto designado como 'Debate abierto sobre los puntos'."
  - "El rol del moderador debe ser ejemplar, manteniendo la formalidad y gestionando las solicitudes de palabra."

pdf_design:
  logo_path: assets/logo.png
  company_name: "STAR Software | star-software.net"

listas_predefinidas:
  proyectos:
    - "Gestora"
    - "Gestora System"
    - "Mantenimiento General"
  lugares:
    - "Stage Discord"
    - "Sala de Juntas 1"
    - "Oficina Principal"
    - "Llamada de Google Meet"
    - "Llamada de Zoom"
  personas:
    - "Mario Moreno"
    - "Alex Macias"
    - "Romel Yugcha"
    - "Ander Endara"
    - "Diego Jimenez"
    - "Henry Sosapanta"
    - "Jordan Herrera"
    - "Bryan Castillo"

documentos:
  - nombre: "Acta de Reunión"
    nombre_corto: "Actas"
    modulo: "actas"
    icon: "assets/icons/actas.png"
    descripcion: "Genera actas de reunión profesionales con un formato estandarizado."
  - nombre: "Acuerdo de Confidencialidad"
    nombre_corto: "NDA"
    modulo: "nda"
    icon: "assets/icons/nda.png"
    descripcion: "Crea Acuerdos de No Divulgación (NDA) para proteger información sensible."
