from PyInstaller.utils.hooks import collect_all

# Collect everything from customtkinter and PIL
datas, binaries, hiddenimports = collect_all('customtkinter')
_, _, pillow_imports = collect_all('PIL')

# Add additional hidden imports that might be needed
hiddenimports.extend([
    'tkinter',
    'tkinter.ttk',
    'tkinter.filedialog',
    'tkinter.messagebox',
    'darkdetect',
    'PIL',
    'PIL._tkinter_finder',
    'PIL._imaging',
    'PIL._imagingft',
    'PIL._imagingmath',
    'PIL._imagingtk',
    'PIL._webp',
    'PIL.BmpImagePlugin',
    'PIL.BufrStubImagePlugin',
    'PIL.CurImagePlugin',
    'PIL.DcxImagePlugin',
    'PIL.EpsImagePlugin',
    'PIL.FitsStubImagePlugin',
    'PIL.FliImagePlugin',
    'PIL.FpxImagePlugin',
    'PIL.GbrImagePlugin',
    'PIL.GifImagePlugin',
    'PIL.GribStubImagePlugin',
    'PIL.Hdf5StubImagePlugin',
    'PIL.IcnsImagePlugin',
    'PIL.IcoImagePlugin',
    'PIL.ImImagePlugin',
    'PIL.ImtImagePlugin',
    'PIL.IptcImagePlugin',
    'PIL.JpegImagePlugin',
    'PIL.McIdasImagePlugin',
    'PIL.MicImagePlugin',
    'PIL.MpegImagePlugin',
    'PIL.MspImagePlugin',
    'PIL.PalmImagePlugin',
    'PIL.PcdImagePlugin',
    'PIL.PcxImagePlugin',
    'PIL.PdfImagePlugin',
    'PIL.PixarImagePlugin',
    'PIL.PngImagePlugin',
    'PIL.PpmImagePlugin',
    'PIL.PsdImagePlugin',
    'PIL.SgiImagePlugin',
    'PIL.SpiderImagePlugin',
    'PIL.SunImagePlugin',
    'PIL.TgaImagePlugin',
    'PIL.TiffImagePlugin',
    'PIL.WebPImagePlugin',
    'PIL.WmfImagePlugin',
    'PIL.XbmImagePlugin',
    'PIL.XpmImagePlugin',
    'PIL.XVThumbImagePlugin'
])